### ISSUE TITLE
Synthetic data workshop

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/QUIPP-collab#122]
Our contributions:

## Presentation on QUIPP
- 15 mins presentation
- 5 minute follow on discussion
- Use first part of CW20 presentation?

## Round table discussion at the end
- 20-40 minutes
- Evaluation metrics + future directions

Please write down ideas here about the round table discussion and the presentation. Also you can edit the slides directly here:
https://thealanturininstitute.sharepoint.com/:p:/s/QUIPP/EYuOMc69zxZPjD2dkNqou_YB_Yh0PTGg9M4jF-9mIXMddQ?e=FqUQf7

**Comment by gmingas** [comment]
Round table discussion questions (a few ideas from Oliver and I):

Applications:
- What are the application areas where we see the highest demand for data synthesis and why?

Synthesis algorithms:
- What are the most used synthetic algorithms in realistic settings in industry, public sector and academia?
  - Specifically for tabular data, time series data, spatial data, graph data.
- Are there any other commonly used algorithms apart from GANs, VAEs, multiple imputation/model-based and microsimulation techniques?
- What are the biggest challenges for each synthetic/generative model type, focusing on imputation and GANs/VAEs?

Privacy:
- How do data publishing organisations/providers assess the adequecy of a privacy-preserving synthesis algorithm? 
  - To what extent are differential privacy, plausible deniability, k-anonymity and motivated intruder metrics (e.g. disclosure risk) accepted guarantees when publishing datasets? 
  - Are they understood?
  - Are there differences between research areas/fields?
- What are the main issues with differential privacy approaches when synthesising datasets? 
  - Slow for realistic datasets? Bad utility?
- What *data-driven/data-centric* metrics can be used to assess synthetic dataset privacy? 
  - Are any of them practical for real datasets? We can give the example of Minimax and other algorithms that do not seem practical.
  - *Definition*: Data-driven is a metric that is decoupled from the synthetic algorithm, i.e. it can be evaluated using only the original and synthetic datasets. This is in contrast to method-dependent privacy which happens when a synthetic algorithm is private by design.
- Are there any approaches that offer "weaker" privacy guarantees than differential privacy but are easier to use in data synthesis settings?

Utility:
- What utility metrics do you recommend?
  - e.g. Model peformance, correlation, data distribution distances, other ML tasks. 
  - Specifically for particular types of data, e.g. graph, time series, geolocation, etc
- Are synthetic data users interested in overall utility of the dataset or only for their own application (e.g. a specific model they want to train)?

**Comment by gmingas** [comment]
Also, regarding the format, we know that ~60 people have been invited/expressed interest, therefore it is likely that there will at least 10-20 in the discussion at the end.

After discussing with Oliver, these are a few things we could do:
- Start with a few questions to everyone where we can visualise the answers live using an app. These could help warm up the discussion and also we can choose them so that we get useful info for QUIPP specifically.
- Separate people into breakout rooms with one QUIPP moderator in each. Ask the same questions to all groups and keep notes in a common hackmd (similar to recent EDI workshop).
- Bring everyone together and present main findings from each group.
- Repeat with different people split and different questions if needed.
- Discuss the possibility of a new Turing interest group or a second meetup.
- Discuss the possiblity of a quipp hackathon, where people would bring their problems specs or data (could be a toy sample or an artificial equivalent of the real data) and we would work on making QUIPP work for that problem.

**Comment by gmingas** [comment]
Live poll questions:
- Why are you interested in synthetic data? --> multiple choice (researcher on developing generators/metrics, want to release data, want to perform analysis on sensitive data, other)
- Which platform are you using for releasing sensitive data? --> multiple choice (writing my own code for synthesis, manual de-identification, SDGym, QUIPP, Privitar, OpenMined, Other open description)
- Which types pf synthetic data generators are you interested in or using? --> word-cloud or multiple choice (...)
- What is a good privacy metric? --> word-cloud or multiple choice (...)
- What is a good data-centric privacy metric? --> word-cloud or multiple choice (...)
- What is a good utility metric for your type of data? --> word-cloud

**Comment by gmingas** [comment]
Links to documents generated during the workshop:
- Notes from the talks [here](https://hackmd.io/PKrZDFA5QYC2ZarFE_1-oA)
- Answers to poll questions [here](https://presenter.ahaslides.com/share/1604530945954-tzx5klhlua?presenting=true)
- Round table questions and notes [here](https://hackmd.io/7kdYzmt-RiKWiwRdiQA5Jg)
- The event was recorded
