### ISSUE TITLE
Apply for ethics approval

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/QUIPP-collab#9]
We should do this as soon as possible and certainly before we receive any data.

[Apply on Turing Complete](https://turingcomplete.topdesk.net/tas/public/ssp/content/serviceflow?unid=2e579708ee364171b58eb4c86e5ed140)

**Comment by gmingas** [comment]
Do we need to do this before we access any data outside Turing systems, e.g. UCL SH?

**Comment by martintoreilly** [comment]
@gmingas Yes we do. I took a quick look at the form and got to "Before proceeding, you must ascertain if you need Health Research Authority approval for this research. Liaise with the EAG directly." due to answering yes to the NHS data question.

**Comment by gmingas** [comment]
I want to apply for this but I have a few questions:

One of the fields in the form requires the following:
> Please cover:
> • the type of data
> • the amount of data in the sample, e.g. number of people, items, variables, months, years covered in the data
> • the sources of the data, e.g. the datasets that will be used, who they were created by, where they are accessible from
> • if known, where and how the data to be used was collected
> • a brief description of the research to be carried out and the methods that will be used

Since we do not know the exact data we are going to use, do we just give some realistic examples of datasets we could use (e.g. UCL dataset)? Or reply more generally, saying that it is not yet clear what we are going to use but it is likely to involve data from healthcare, finance, etc?

Also, since we probably want to be able to use NHS data, we will need to be in touch with EAG (see Martin's message above). I can write an email before we submit. Are there any questions you want me to include in the email?

**Comment by martintoreilly** [comment]
I think our application should reflect the data we are currently planning to access. We can update our ethics approval alongside any process we go through to gain access to specific real world data sets. If we already have access to UCL data, then we should describe it.

**Comment by gmingas** [comment]
This was submitted on the 23rd of November. Submission can be found [here](https://hackmd.io/MR40sQQfQ5CUvQBb8UtnzA?both)
